sonar.projectKey=Haon19_SEP2_week5_assignment
sonar.projectName=SEP2_week5_assignment
sonar.organization=haon19
sonar.sources=src
sonar.java.binaries=target/classes
sonar.host.url=https://sonarcloud.io


# run with:
#    mvn clean verify sonar:sonar "-Dsonar.projectKey=untitled" "-Dsonar.token=$env:SONAR_TOKEN" "-Dsonar.host.url=http://localhost:9000"